services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
      
    command: npm run server
    # volumes:
    #   - './:/usr/src/app'
      # - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.jthunsj.mongodb.net/
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongo
    networks:
      - private
      - public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G 
  #  commented out because I don' need this for mongo atlas     
  # mongo:
  #     image: mongo:latest
  #     environment:
  #       - MONGO_INITDB_ROOT_USERNAME=/run/secrets/user
  #       - MONGO_INITDB_ROOT_PASSWORD=/run/secrets/pw
  #     secrets:
  #       - user
  #       - pw
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - mongo_data:/data/db
  #     restart: always
  #     networks:
  #       - private
  #     deploy:
  #       resources:
  #         limits:
  #           cpus: '0.50'
  #           memory: 500M

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    networks:
      - public
    volumes:
      - frontend_node_modules:/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    deploy:
        resources:
          limits:
            cpus: '0.70'
            memory: 2G

# secrets:
#   user:
#     file: "../secrets/user.txt"
#   pw:
#     file: "../secrets/pw.txt"
networks:
  private: {}
  public: {}

volumes:
  # mongo_data:
  #   driver: local
  frontend_node_modules:
    driver: local

  
     

